version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3004" # Docker dışındaki 3005 portunu, container içindeki 3004 portuna yönlendiriyoruz
    environment:
      NODE_ENV: production
